spring:
  data:
    mongodb:
      uri: ${URL_MONGO_COMMUNION:mongodb+srv://divinex:qiwTHEeeJVj2M3dp@divinex.txdcsgc.mongodb.net/divinex?retryWrites=true&w=majority}
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  client:
    #  ms-storage:
    # url: ${URL_VG_MS_STORAGE:https://vg-ms-storage-production.up.railway.app}
    ms-users:
      url: ${URL_VG_MS_USERS:https://vg-ms-user-production-x1.up.railway.app}
    ms-income:
      url: ${URL_VG_MS_INCOME:https://vg-ms-income-production.up.railway.app}

feign:
  client:
    config:
      ms-storage:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
server:
  port: ${PORT_COMMUNION:7003}

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api/marriage

# Microservice health meter
management:
  endpoint:
    health:
      show-details: always

